### ISSUE TITLE
update sitemap handling

### ISSUE THREAD

**Issue by coreykn** [keycdn/cdn-enabler#19]
WordPress 5.5 introduces basic, extensible XML sitemaps functionality into WordPress core: https://make.wordpress.org/core/2020/07/22/new-xml-sitemaps-functionality-in-wordpress-5-5/

As of version 1.0.9 with the default settings the CDN Enabler plugin is rewriting the `xml-stylesheet` declaration in the `*.xml` files (e.g. `wp-sitemap.xml` or `wp-sitemap-posts-post-1.xml`), for example:

```
<?xml-stylesheet type="text/xsl" href="https://www.example.com/wp-sitemap-index.xsl" ?>
<?xml-stylesheet type="text/xsl" href="https://cdn.example.com/wp-sitemap-index.xsl" ?>
```

Further, the CDN Enabler plugin is also rewriting the `xsl:output` element in the `wp-sitemap.xsl` file (unless the  Relative Path setting is disabled), for example:

```
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:output method="html" encoding="UTF-8" indent="yes"https://cdn.example.com/>
```

This is causing the sitemaps to not load correctly. Current workaround to fix this issue would be adding `xsl` to the Exclusions setting (e.g. `.php,xsl`).

WordPress topic: https://wordpress.org/support/topic/breaks-sitemap-xsl-generated-by-wordpress-5-5/

**Comment by vzeazy** [comment]
Thanks for investigating and locating the issue.

Have attempted the exclusion approach, but couldn’t get it to work. Instead, ended up just adding a filter to xsl output using wp_sitemaps_stylesheet_content (adding an additional space into the xls file where the markup was being broken).

This seems to have solved the issue for now.

If anyone finds it useful, here is my filter:

function webme_sitemap_xsl($original) {
return str_replace(‘indent=”yes”/>’, ‘indent=”yes” />’, $original);
}
add_filter(‘wp_sitemaps_stylesheet_content’, ‘webme_sitemap_xsl’);

Look forward to a permanent solution with the regex causing it in the first place. 🙂
