### ISSUE TITLE
Add filter/constant to set "cdn_enabler.url" (improvement suggestion)

### ISSUE THREAD

**Issue by mibu31** [keycdn/cdn-enabler#20]
Hi there,
Is there any chance we can get a filter or constant added to override the "CDN URL" var?
This should be settable programmatically / configurable in code imo.
Cheers.

**Comment by benjibee** [comment]
I came here to add the same suggestion. A constant defined in `wp-config.php` along the lines of `WP_SITEURL` would be really helpful as I have many projects where I sync the database to a staging server and local dev and not having this override is a bit of a headache!

**Comment by coreykn** [comment]
Would using the [`pre_option_{$option}`](https://developer.wordpress.org/reference/hooks/pre_option_option/) and/or [`option_{$option}`](https://developer.wordpress.org/reference/hooks/option_option/) filter hooks work?
