### ISSUE TITLE
WP-CLI command to be able to enable HTTPS setting only

### ISSUE THREAD

**Issue by lukecav** [keycdn/cdn-enabler#22]
Would also be helpful for enabling different settings all from WP-CLI. Same with setting the CDN URL.

**Comment by coreykn** [comment]
Would using [`wp option update`](https://developer.wordpress.org/cli/commands/option/update/) work for this or do you have a different preference with how you'd like to interact with the CDN Enabler settings from the command line?

**Comment by lukecav** [comment]
Maybe a command like;

`wp cache-enabler enable-https`

**Comment by coreykn** [comment]
Thanks for your feedback. Just so you're aware, the changes proposed in PR #23 will make it so the CDN HTTPS setting will no longer exist. If you have any feedback on those changes please feel free to leave a comment in that pull request.

As far as this enhancement request goes, we don't plan on introducing this type of support in the branch that will be released in the near future, but will be able to revisit adding support for controlling the CDN Enabler settings from WP-CLI at a later point of time.
