### ISSUE TITLE
[Feature Request] Allow purging the CDN via the plugin

### ISSUE THREAD

**Issue by isaumya** [keycdn/cdn-enabler#3]
Hi,
I think it would be really great if you guys allow purging the CDN via the plugin. WHether that's the whole CDN purge or some url purge. It would really help everyone as users don't have to login to their account to purge the CDN

**Comment by dramaturg** [comment]
We implemented full zone purges for KeyCDN in #4 which will be released soon.

**Comment by isaumya** [comment]
Thank you for implementing this. I think it would be better if you allow url based purge as well in near future.
