### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by mikemarinescu** [keycdn/cdn-enabler#52]
Hello,

I'm looking to add a license for our project that is based off this project:

https://github.com/vultr/cdn-enabler

What license are you offering this code under - would it be Apache 2.0? 

Thank you!

**Comment by svenba** [comment]
Author: KeyCDN
Author URI: https://www.keycdn.com

**License: GPLv2 or later**

**Copyright (C) 2024 KeyCDN**
