### ISSUE TITLE
Integration with visual composer plugin (WP Bakery)

### ISSUE THREAD

**Issue by francoboy7** [keycdn/cdn-enabler#6]
Some modules of visual composer load images without going through the CDN
for example the "post masonry grid" module of visual composer have that issue.
The DIV tag it creates uses the background-image CSS to set the image. However the image URL is not the CDN one. 

You can see the problem happening on that webpage : [URL](https://globalmedic.ca/volunteer/) under the "meet some of our amazing volunteers"

`<div class="vc_gitem-zone vc_gitem-zone-a vc-gitem-zone-height-mode-auto vc-gitem-zone-height-mode-auto-3-4 vc_gitem-is-link" style="background-image: url('https://globalmedic.ca/wp-content/uploads/ivana.jpg') !important;">`

**Comment by isaumya** [comment]
Stop using visual composer, it's disgusting.
