### ISSUE TITLE
CDN URL not being inserted with image urls pass through wp_get_attachment_metadata & wp_upload_dir

### ISSUE THREAD

**Issue by isaumya** [keycdn/cdn-enabler#8]
Hi,
I'm using a WordPress gallery plugin named [Global Gallery](https://codecanyon.net/item/global-gallery-wordpress-responsive-gallery/3310108) for showing up galleries on my website. Now the problem is that all the images showing up in the gallery is using the direct URL instead of the CDN URL even though the CDN Enabler is enabled. Also please note that I'm using the WordPress Media Gallery for images, not any third party image pullings.

After I contacted the plugin author, he said that if I'm using the WordPress media, then it should be showing up the CDN URLs as his plugin uses all WP in-built functions to show up wp-images.

After asking him he said in his plugin he is mostly using `wp_get_attachment_metadata()` and `wp_upload_dir()` function and he also provided a snippet from his plugin:

```
From my side, I’m already doing the best I can.
This is the code I use

function gg_img_id_to_path($img_src) {
	if(is_numeric($img_src)) {
		$wp_img_data = wp_get_attachment_metadata((int)$img_src);
		if($wp_img_data) {
			$upload_dirs = wp_upload_dir();
			$img_src = $upload_dirs['basedir'] . '/' . $wp_img_data['file'];
		}
	}
	return $img_src;
}
```

So, I'm reporting this to you for a check so that if there is an issue you can fix it so that it supports the CDN using CDN enabler.

**Comment by svenba** [comment]
Please note that the CDN Enabler can not rewrite images injected with JavaScript.

**Comment by isaumya** [comment]
Hi, any update on these? Please note that the image urls are not getting injected via javascript. It is being injected via PHP by using the following function:

```
$wp_img_data = wp_get_attachment_metadata((int)$img_src);
if($wp_img_data) {
    $upload_dirs = wp_upload_dir();
    $img_src = $upload_dirs['baseurl'] . '/' . $wp_img_data['file'];
}
```

Can anyone tell me how can this issue be resolved?
